### ISSUE TITLE
Changing settings clears user card data

### ISSUE THREAD

**Issue by mstamour12** [Dennymu/MyHomeTab#1]
Checking and un-checking the Show Clock setting will reset cards back to default

**Comment by mstamour12** [comment]
Seems to only happen when the New Tab page is open in one tab and Settings page is open in another tab. If you add a new card in the New Tab page, change a setting on the Settings page, then refresh the New Tab page that newly-added card disappears. May be a bug but it's also not being used as intended to recreate

**Comment by Dennymu** [comment]
A fix would require loading data prior to setting. Could slow down performance significantly and unintentionally add a bug where an edit isn't saved before the browser tab is closed. Will need discussion/testing
